# raise lançar expition (ERROR)

print(123)
raise ValueError("ERROR !!!") # lancça esse error editado
print(456)